---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(sf)
library(ggthemes)
library(class)
```

```{r}
HFPA.data %>%
  group_by(year) %>%
  summarize(mean = mean(HFPA, na.rm = T),
            sd = sd(HFPA, na.rm = T))
```


```{r}
HFPA.data %>%
  group_by(year) %>%
  mutate(Priority.Area = case_when(HFPA >= (mean(HFPA, na.rm = T) + sd(HFPA, na.rm = T)) ~ '1 SD Above Mean',
                   HFPA <= (mean(HFPA, na.rm = T) - sd(HFPA, na.rm = T)) ~ '1 SD Below Mean',
                   TRUE ~ 'Not Anomalous'
                   ))
```

```{r}
num.anomalous = HFPA.data %>%
  group_by(year, Priority.Area) %>%
  summarize(count = n())
num.anomalous %>%
  filter(Priority.Area == '1 SD Above Mean') %>%
  ggplot(mapping = aes(x = year, y = count)) +
  geom_col()
```
```{r}
HFPA.data %>%
  ungroup() %>%
  mutate(Priority.Area = ordered(x = Priority.Area, levels = c('1 SD Above Mean', 'Not Anomalous', '1 SD Below Mean'))) %>%
  ggplot(aes(fill = Priority.Area, text = GEOID)) +
    geom_sf(color = 'black', size = .2) +
    facet_wrap('year') +
    scale_fill_discrete(type = c('#ca0020', 'White', '#abd9e9')) +
    #scale_fill_brewer(palette = 'RdGy') +
    theme_void() +
    theme(strip.background = element_rect(fill = 'gold1'), 
          panel.background  = element_rect(fill = 'grey')) +
    labs(title = 'Priority Areas by Year', fill = 'Priority Area')
```

```{r}
HFPA.knn = HFPA.data %>%
  mutate(Priority.Class = 
           case_when(Priority.Area == '1 SD Above Mean' ~ 1,
                     T ~ 0),
         Priority.Class = as.factor(Priority.Class)) %>%
  st_set_geometry(NULL)
```

```{r}
write_csv(HFPA.knn, 'HFPA_class.csv')
```


```{r}
```


```{r}
```

